config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')), 
    path('', include('snsapp.urls')), 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

snsapp/urls.py
from django.urls import path
from . import views
from .views import Home, MyPost, CreatePost, DetailPost, UpdatePost, DeletePost,\
                   LikeHome, FollowHome, FollowDetail, FollowList, LikeDetail

app_name = 'snsapp'
# app_name = 'register'
urlpatterns = [
   path('', Home.as_view(), name='home'),             
   path('mypost/', MyPost.as_view(), name='mypost'),
   path('detail/<int:pk>', DetailPost.as_view(), name='detail'),  
   path('detail/<int:pk>/update', UpdatePost.as_view(), name='update'),
   path('detail/<int:pk>/delete', DeletePost.as_view(), name='delete'),
   path('create/', CreatePost.as_view(), name='create'),
   path('edit/<int:pk>/', views.edit, name="edit"),
   path('like-home/<int:pk>', LikeHome.as_view(), name='like-home'),
   path('like-detail/<int:pk>', LikeDetail.as_view(), name='like-detail'),
   path('follow-home/<int:pk>', FollowHome.as_view(), name='follow-home'),
   path('follow-detail/<int:pk>', FollowDetail.as_view(), name='follow-detail'),
   path('follow-list/', FollowList.as_view(), name='follow-list'),
]

accounts/models.py
from django.db import models

# Create your models here.

snsapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    like = models.ManyToManyField(User, related_name='related_post', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-created_at"]


class Connection(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    following = models.ManyToManyField(User, related_name='following', blank=True)

    def __str__(self):
        return self.user.username

snsapp/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

    def send_email(self):
        # send email using the self.cleaned_data dictionary
        pass

accounts/views.py
from django.shortcuts import render

# Create your views here.

snsapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User

from .models import Post, Connection


class Home(LoginRequiredMixin, ListView):
    """HOMEページで、自分以外のユーザー投稿をリスト表示"""
    model = Post
    template_name = 'list.html'

    def get_queryset(self):
        """リクエストユーザーのみ除外"""
        return Post.objects.exclude(user=self.request.user)
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        #get_or_createにしないとサインアップ時オブジェクトがないためエラーになる
        context['connection'] = Connection.objects.get_or_create(user=self.request.user)
        return context
    

class MyPost(LoginRequiredMixin, ListView):
    """自分の投稿のみ表示"""
    model = Post
    template_name = 'list.html'

    def get_queryset(self):
        return Post.objects.filter(user=self.request.user)


class CreatePost(LoginRequiredMixin, CreateView):
    """投稿フォーム"""
    model = Post
    template_name = 'create.html'
    fields = ['title', 'content']
    success_url = reverse_lazy('mypost')

    def form_valid(self, form):
        
        """投稿ユーザーをリクエストユーザーと紐付け"""
        form.instance.user = self.request.user
        return super().form_valid(form)


class DetailPost(LoginRequiredMixin, DetailView):
    """投稿詳細ページ"""
    model = Post
    template_name = 'detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['connection'] = Connection.objects.get_or_create(user=self.request.user)
        return context


class UpdatePost(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """投稿編集ページ"""
    model = Post
    template_name = 'update.html'
    fields = ['title', 'content']
    success_url = reverse_lazy('snsapp:list.html')

    def get_success_url(self,  **kwargs):
        """編集完了後の遷移先"""
        pk = self.kwargs["pk"]
        return reverse_lazy('detail', kwargs={"pk": pk})
    
    def test_func(self, **kwargs):
        """アクセスできるユーザーを制限"""
        pk = self.kwargs["pk"]
        post = Post.objects.get(pk=pk)
        return (post.user == self.request.user) 

class EditView(View):
    model = Post
    def get(self, request, pk, *args, **kwargs):

        #編集対象を特定してレンダリング
        pk = Post.objects.filter(id=pk).first()
        context = { "post":Post }

        return render(request,'edit.html',context)

    def post(self, request, pk, *args, **kwargs):

#         #編集対象を特定
        Post   = Post.objects.filter(id=pk).first()

#         #instanceに編集対象を指定して、request.POSTをバリデーション(※ これで編集対象の内容が書き換わる。もし、instanceが存在しない場合、新しく作られる。)
        form    = Post(request.POST,instance=Post)

        if form.is_valid():
            print("バリデーションOK")
            form.save()
        else:
            print("バリデーションNG")

        return redirect("snsapp:index")

edit    = EditView.as_view()

class DeletePost(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """投稿編集ページ"""
    model = Post
    template_name = 'delete.html'
    success_url = reverse_lazy('snsapp:mypost')
    
    
    def test_func(self, **kwargs):
        """アクセスできるユーザーを制限"""
        pk = self.kwargs["pk"]
        post = Post.objects.get(pk=pk)
        return (post.user == self.request.user) 


###############################################################
#いいね処理
class LikeBase(LoginRequiredMixin, View):
    """いいねのベース。リダイレクト先を以降で継承先で設定"""
    def get(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        related_post = Post.objects.get(pk=pk)

        if self.request.user in related_post.like.all():
            obj = related_post.like.remove(self.request.user)
        else:
            obj = related_post.like.add(self.request.user)  
        return obj


class LikeHome(LikeBase):
    """HOMEページでいいねした場合"""
    def get(self, request, *args, **kwargs):
        super().get(request, *args, **kwargs)
        return redirect('snsapp:home')


class LikeDetail(LikeBase):
    """詳細ページでいいねした場合"""
    def get(self, request, *args, **kwargs):
        super().get(request, *args, **kwargs)
        pk = self.kwargs['pk'] 
        return redirect('snsapp:detail', pk)
###############################################################


###############################################################
#フォロー処理
class FollowBase(LoginRequiredMixin, View):
    """フォローのベース。リダイレクト先を以降で継承先で設定"""
    def get(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        target_user = Post.objects.get(pk=pk).user

        my_connection = Connection.objects.get_or_create(user=self.request.user)

        if target_user in my_connection[0].following.all():
            obj = my_connection[0].following.remove(target_user)
        else:
            obj = my_connection[0].following.add(target_user)
        return obj

class FollowHome(FollowBase):
    """HOMEページでフォローした場合"""
    def get(self, request, *args, **kwargs):
        super().get(request, *args, **kwargs)
        return redirect('snsapp:home')

class FollowDetail(FollowBase):
    """詳細ページでフォローした場合"""
    def get(self, request, *args, **kwargs):
        super().get(request, *args, **kwargs)
        pk = self.kwargs['pk'] 
        return redirect('snsapp:detail', pk)
###############################################################


class FollowList(LoginRequiredMixin, ListView):
    """フォローしたユーザーの投稿をリスト表示"""
    model = Post
    template_name = 'list.html'

    def get_queryset(self):
        """フォローリスト内にユーザーが含まれている場合のみクエリセット返す"""
        my_connection = Connection.objects.get_or_create(user=self.request.user)
        all_follow = my_connection[0].following.all()
        return Post.objects.filter(user__in=all_follow)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['connection'] = Connection.objects.get_or_create(user=self.request.user)
        return context

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
      integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp"
      crossorigin="anonymous"
    />
    {% block customcss %} {% endblock customcss %}

    <title>SNSアプリサンプル</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'snsapp:home' %}">Home</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link" href="{% url 'snsapp:follow-list' %}"
              >フォローユーザーの投稿</a
            >
            <a class="nav-link" href="{% url 'snsapp:mypost' %}">自分の投稿</a>
            <a class="nav-link" href="/accounts/logout/">ログアウト</a>
            <a
              class="nav-link btn btn-success"
              href="{% url 'snsapp:create' %}"
              role="button"
              >投稿</a
            >
          </div>
        </div>
        <div>{{request.user.username}}さん</div>
      </div>
    </nav>

    {% block content %} {% endblock content %}
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
      integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
      integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/connection.html
{% extends 'base.html' %}
{% load static %}

{% block customcss %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock customcss %}

{% block content %}
<div class="container mt-3">
    {% for item in object_list %}
    <p>タイトル：<a href="#">{{item.author}}</a></p>
    {% endfor %}
</div>
{% endblock content %}

templates/create.html
{% extends 'base.html' %}


{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="投稿">
</form>
{% endblock content %}

templates/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'snsapp:delete' object.id %}" method="mypost">
    {% csrf_token %}
    <p>本当に削除してもよろしいですか?</p>
    <input type="submit" value="削除する">
</form>
{% endblock content %}

templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block customcss %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock customcss %}

{% block content %}
<div class="container">
    <div class="alert alert-success" role="alert">
        <p>タイトル：{{object.title}}</p>
        <p>投稿者：{{object.user}}</p>
        <p>コメント：{{object.content}}</p>

        {% if request.user in object.like.all %}
        <a href="{% url 'snsapp:like-detail' object.pk %}" class="like-btn add-color" tabindex="-1" role="button" aria-disabled="true"><i class="fas fa-heart"></i></a>{{object.like.count}}
        {% else %}
        <a href="{% url 'snsapp:like-detail' object.pk %}" class="like-btn" tabindex="-1" role="button" aria-disabled="true"><i class="far fa-heart"></i></a>{{object.like.count}}
        {% endif %}

        {% if object.user in connection.0.following.all %}
        <a href="{% url 'snsapp:follow-detail' object.pk %}" class="btn btn-danger ms-3" tabindex="-1" role="button" aria-disabled="true">フォロー解除</a>
        {% else %}
        <a href="{% url 'snsapp:follow-detail' object.pk %}" class="btn btn-primary ms-3" tabindex="-1" role="button" aria-disabled="true">フォロー</a>
        {% endif %}

        {% if object.user == request.user %}
        <a href="{% url 'snsapp:update' object.pk %}" class="btn btn-primary ms-3" tabindex="-1" role="button" aria-disabled="true">編集</a>
        <a href="{% url 'snsapp:delete' object.pk %}" class="btn btn-danger ms-3" tabindex="-1" role="button" aria-disabled="true">削除</a>
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/edit.html
<div>
  <a href="{% url 'snsapp:detail' object.id %}">戻る</a>
  </div>
  
  <form action="{% url 'snsapp:edit' object.id %}" method="POST">{% csrf_token %}
    <table>
      <tr>
        <th>タイトル</th>
        <td>{{ form.title }}</td>
      </tr>
      <tr>
        <th>テキスト</th>
        <td>{{ form.text }}</td>
      </tr>
    </table>
    <button class="btn" type="submit">保存</button>
  </form>

templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="ja" dir="ltr">
<head>
<meta charset="utf-8">
<title></title>
<link rel="stylesheet" href='{% static "App_Folder_css/css/style.css" %}'/>

</head>
<body>
 <h1><font color="red">{{ UserID }}</font>さんようこそ！！</h1>

 <p> ログアウトは
 <a href="{% url 'snsapp:Logout' %}">こちら</a>
 </p>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>簡易掲示板</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>

    <main class="container">
        <form method="POST">
            {% csrf_token %}
            <textarea class="form-control" name="comment"></textarea>
            <input type="submit" value="送信">
        </form>

        {% for topic in topics %}
        <div class="border">
            {{ topic.comment }}

            <form action="{% url 'snsapp:delete' object.id %}" method="POST">
                {% csrf_token %}
                <input class="btn btn-danger" type="submit" value="削除">
            </form>

            <!--↓ここに編集のリンクを追加-->
            <a class="btn btn-success" href="{% url 'snsapp:edit' object.id %}">編集</a>
        </div>
        {% endfor %}

    </main>
</body>
</html>

templates/list.html
{% extends 'base.html' %}
{% load static %}

{% block customcss %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock customcss %}

{% block content %}
<div class="container mt-3">
    {% for item in object_list %}
    <div class="alert alert-success" role="alert">
        <p>タイトル：<a href="{% url 'snsapp:detail' item.pk %}">{{item.title}}</a></p>
        <p>投稿者：{{item.user.username}}</p>    

        {% if request.user in item.like.all %}
        <a href="{% url 'snsapp:like-home' item.pk %}" class="like-btn add-color" tabindex="-1" role="button" aria-disabled="true"><i class="fas fa-heart"></i></a>{{item.like.count}}
        {% else %}
        <a href="{% url 'snsapp:like-home' item.pk %}" class="like-btn" tabindex="-1" role="button" aria-disabled="true"><i class="far fa-heart"></i></a>{{item.like.count}}
        {% endif %}

        {% if item.user in connection.0.following.all %}
        <a href="{% url 'snsapp:follow-home' item.pk %}" class="btn btn-danger ms-3" tabindex="-1" role="button" aria-disabled="true">フォロー解除</a>
        {% else %}
        <a href="{% url 'snsapp:follow-home' item.pk %}" class="btn btn-primary ms-3" tabindex="-1" role="button" aria-disabled="true">フォロー</a>
        {% endif %}
    </div>
    {% endfor %}
</div>
{% endblock content %}

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="ja" dir="ltr">
<head>
<meta charset="utf-8">
<title></title>
<link rel="stylesheet" href='{% static "App_Folder_css/style.css" %}'/>

</head>
<body>
<h1>ログイン画面</h1>

<div class="reg">
  <form method="post" action="{% url 'snsapp:Login' %}">
    {% csrf_token %}

    <table class="reg_form">
    <tr>
    <td><label for="userid">ユーザーID:</label></td>
    <td><input type="text" name="userid"></td>
    <td><label for="password">パスワード：</label></td>
    <td><input type="password" name="password"></td>
    </tr>
    </table>

    <input type="submit" class="btn" value="Login">
 </form>
</div>
   <p class="message">アカウントをお持ちですか？：
   <a href="{% url 'snsapp:register' %}">アカウントを作成</a>
   </p>
</body>
</html>

templates/update.html
{% extends 'base.html' %}


{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <button><a class="btn" href="{% url 'snsapp:edit' object.id %}">編集</a></button>
</form>
{% endblock content %}